server:
  port: 8015

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    database: default
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    url: jdbc:h2:file:./db/test.db
    url: jdbc:h2:mem:testdb
#    url: jdbc:derby:test;create=true
    username: sa
    password:
    driverClassName: org.h2.Driver
#    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
