zuul:
  routes:
    resource:
      path: /api/**
      url: http://localhost:8092/account/
      sensitiveHeaders:
#    user:
#      path: /index/**
#      url: http://localhost:8091/auth/index
#      sensitiveHeaders:
    auth:
      path: /auth/**
      url: http://localhost:8091/auth/
      sensitive-headers:

logging:
  level:
    org.springframework.security: DEBUG

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:8080/auth/oauth/token
      userAuthorizationUri: http://localhost:8080/auth/oauth/authorize
      clientId: maingateway
      preEstablishedRedirectUri: http://localhost:8080/login
      registeredRedirectUri: http://localhost:8080/login
      useCurrentUri: false

    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimUKhvBhsoeSM3HkIOP/Y3RXjvonBlZnLj8oO92TyAKG53lmAoK0wZ5MTZPsfrOz2Z7CeAp6mPhUANX2RUoFwVzG7rJmgWyqGmGFNBmtYL+uVqQ80TzWi5zyzXTxgVMWiCqqw/u4AeE1qhN8chnGwhUBnpgPAPd8v57mIwg0n5JxjdYe7pgHlpvt8ZXTXd1KBxB5K7WjNlCfMf75ZEeBaplxsSfJUwKbnHQKWcY3NnpjkVR8y4jviAbkOHmGMaliM7fcsLzbosBUPDQuNlvYdjPBRfH6MMPeXRW6On3u0Um9wIYmkQS+AEgHCq4UuLOnTTqqxnGkwFYeMAAXmRyMtQIDAQAB
          -----END PUBLIC KEY-----
#debug: true
#
#spring:
#  aop:
#    proxy-target-class: true
#
#security:
#  sessions: NEVER