zuul:

  routes:
    resource:
      path: /resource/**
      url: http://localhost:8091/resource
    user:
      path: /index/**
      url: http://localhost:8091/auth/index
      sensitiveHeaders:

logging:
  level:
    org.springframework.security: DEBUG

#debug: true
#
#spring:
#  aop:
#    proxy-target-class: true
#
#security:
#  sessions: NEVER